
languageCode = 'en-us'
title = 'Dan Luo CV'
theme = "orbit"


# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "john doe"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Dan Dake Luo"
        tagline = "Sr DevOps/Software Engineer"
        avatar = "selfscaled.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: syck40@gmail.com"
        title = "syck40@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+111111"
        title = "+111111"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//drakenor.com"
        title = "drakenor.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/dan-dake-luo/"
        title = "linkedin.com/in/dan-dake-luo/"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/syck40"
        title = "github.com/syck40"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BSc in Biology"
        college = "University of California, Irvine"
        dates = "2002 - 2004"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "Chinese-Mandarin"
        level = "Native"

        [[params.language.list]]
        language = "Chinese-Cantonese"
        level = "Ok"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Sports"

        [[params.interests.list]]
        interest = "Cars"

        [[params.interests.list]]
        interest = "Computing"

        [[params.interests.list]]
        interest = "Gaming"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "A devops/release engineer with 5+ years of software engineer background.  With 10+ years of professional experiences both in and out of the gaming industry.  A true believer of growth mindset."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Sr Release Engineer"
        dates = "2019 - 2021"
        company = "PlayStation, Aliso Viejo"
        details = "As a Sr Release Engineer at Sony Interactive Entertainment, I worked closely with development team responsible for the PlayStation Now streaming service.  I have fullfilled duties such as: \n\nMigrating legacy microservices to on-premise Kubernetes clusters using Docker, Helm and other CNCF technologies.\n\nImproving and maintaining CI/CD systems for different development teams' needs.\n\nArchitect and implement cloud native designs such as service to service mTLS.\n\nDesign and implement public cloud service migration in areas such as infrastructure as code for the organization."

        [[params.jobs.list]]
        position = "DevOps Engineer"
        dates = "2019 - 2019"
        company = "Leaf Group, Santa Monica"
        details = "As a devops engineer in Techo Ops department, my responsibilities were maintaining and supporting the CI/CD infrastructures for public facing websites such as wellandgood.com, livestrong.com, ehow.com.\n\nTasks such as containerization of legacy softwares, administration duties of on-premise Kubernetes clusters, user controls for company AWS accounts.  Spearheaded organizational migration in secrets management using Hashicorp Vault."

        [[params.jobs.list]]
        position = "Software Engineer"
        dates = "2011 - 2019"
        company = "Blizzard Entertainment, Irvine"
        details = "As a software engineer in QA engineering and later Corporate Applications team inside Blizzard, I worked on numerous internal web projects intended for other developers and managers in the company.\n\nI also worked on web applications supporting public facing events like the annual company convention - BlizzCon.  For these projects, I was involved in planning and implementing frontend and backend systems using JavaScript, C# and MSSQL.\n\nLater, I was also in charge of devops/infrastructure tasks for my department using technologies like Docker, Puppet."

        [[params.jobs.list]]
        position = "QA Tester/Automation Engineer"
        dates = "2005- 2011"
        company = "Blizzard Entertainment, Irvine"
        details = "Worked closely with game designers providing feedbacks on gameplay balance, indentifying potential exploits on AAA titles like Diablo III, StarCraft II and multiple World of Warcraft expansions.\n\nAlso worked on automated online checklist system to speed up automated game testing"

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Tools"
        intro = "AWS - Cloudformation, AWS - CDK, Docker, Kubernetes, Jenkins, Gitlab, Envoyproxy, Hashicorp - Vault, Hashicorp - Consul, Hashicorp - Terraform, Ansible"

        [[params.projects.list]]
        title = "Amazon Web Services Solutions Architect - Associate"
        url = "https://www.linkedin.com/in/dan-dake-luo/"
        tagline = "AWS Solutions Architect Associate certified."

        [[params.projects.list]]
        title = "Amazon Web Services Developer - Associate"
        url = "https://www.linkedin.com/in/dan-dake-luo/"
        tagline = "AWS Web Services Developer Associate certified."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Kubernetes & Docker"
        level = "80%"

        [[params.skills.list]]
        skill = "Bash"
        level = "80%"

        [[params.skills.list]]
        skill = "Linux"
        level = "75%"

        [[params.skills.list]]
        skill = "Golang"
        level = "70%"

        [[params.skills.list]]
        skill = "Python"
        level = "70%"

        [[params.skills.list]]
        skill = "C#"
        level = "60%"

        [[params.skills.list]]
        skill = "Javascript & jQuery"
        level = "50%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""


[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "drakeCv"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://cv.drakenor.com?region=us-west-1"
